### ISSUE TITLE
Visual Studio Version

### ISSUE THREAD

**Issue by spuberman7** [usnistgov/CloudSecurityArchitectureTool#3]
Visual Studio project solution file "Cloud Security Rubik's Cube.sln" is incompatible to MS Visual Studio 20120 Pro. Can anyone help?

**Comment by iMichaela** [comment]
Do you mean 2010 Pro or 2012 Pro?

**Comment by spuberman7** [comment]
sorry for typo, it is 2010 MS Visual Studio Pro SP1.

**Comment by nikitawootten** [comment]
The Rubik's Cube was developed on Visual Studio 2013 Express, it is compatible with versions later then that, but I do not believe it is backwards compatible with older versions of Visual Studio.

**Comment by spuberman7** [comment]
hi, all, thank you for helping on this matter.

**Comment by JustKuzya** [comment]
With actual SQL Server you may need to make sure that the connection string is working correctly for your setup. SQL Express allows to use same machine name read from registry, SQL Server is not that easy: for the proper connection string you may need instance name, possibly port number, etc. The easiest thing would be to pull out a connection string sample from the SQL Server Instance of the database you have set up for the Rubik’s Cube and use it in the code instead of the existing one.

If VS 2010 Pro has [SQL Server] or [Data Management] console, you can try to compose the connection string right there from the console inside of the VS2010 to your SQL Server instance. 

BTW, you might also need to comment out the connection string that builds connection string. I’m afraid it assumed that user uses free SQL Express, which associates DB instance name with the machine name.
